In [3]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt  

torch.__version__, pd.__version__, np.__version__ 

('2.2.1+cpu', '2.2.1', '1.26.4')

https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar 
scalar = torch.tensor(7) 
scalar 

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
print(type(scalar)) 
print(type(scalar.item()))
print(scalar.dtype) 
print(scalar.device) 

scalar.item()  # tensor -> int 

<class 'torch.Tensor'>
<class 'int'>
torch.int64
cpu


7

In [8]:
vector = torch.tensor([7, 7]) 
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [13]:
MATRIX = torch.tensor(
    [[7, 8], 
    [9, 10]]
    )

MATRIX 

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9], 
                        [2, 4, 6]]]) 

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [17]:
TENSOR.ndim 

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
# random tensor 
random_tensor = torch.rand(3, 4)  # randn, randint  
random_tensor 

tensor([[0.2237, 0.9912, 0.0367, 0.8852],
        [0.0375, 0.5069, 0.7987, 0.1582],
        [0.7588, 0.8520, 0.8779, 0.9420]])

In [21]:
random_tensor.ndim

2

In [25]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [28]:
# float 32 tensor 
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, device='cpu', requires_grad=False)
float_16_tensor.dtype, float_16_tensor.device, float_16_tensor.requires_grad

(torch.float16, device(type='cpu'), False)

In [32]:
float_32_tensor.type(torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
# matrix multiplication 
t1 = torch.tensor([1, 2, 3]) 
t2 = torch.tensor([4, 5, 6]) 

print(f"{t1} @ {t2} = {t1 @ t2}")
print(torch.matmul(t1, t2)) 

tensor([1, 2, 3]) @ tensor([4, 5, 6]) = 32
tensor(32)


In [42]:
m1 = torch.tensor([[1, 2], 
                   [3, 4], 
                   [5, 6]]) 

m2 = torch.tensor([[7, 8],
                   [9, 10], 
                   [11, 12]])

torch.mm(m1, m2.transpose(0, 1))

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [43]:
t = torch.tensor([[ 23,  29,  35],
                  [ 53,  67,  81],
                  [ 83, 105, 127]]) 

torch.max(t), t.max() 

(tensor(127), tensor(127))

In [45]:
print(torch.max(t, dim=0)) 
print(t.max(dim=0))  # 행을 없애는 방향 

torch.return_types.max(
values=tensor([ 83, 105, 127]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([ 83, 105, 127]),
indices=tensor([2, 2, 2]))


In [52]:
print(torch.argmax(t, dim=0))

tensor([2, 2, 2])


In [49]:
print(torch.mean(t.type(torch.float32))) 
print(torch.mean(t.type(torch.float32), dim=0)) 


tensor(67.)
tensor([53., 67., 81.])


* reshape - 원본 tensor와 메모리 공유 x
* view - 원본 tensor와 메모리 공유 o
* stack - 새로운 축 생성 
* cat - vstack, hstack - 축 생성 없이 이어 붙이기 
* squeeze 
* unsqueeze 
* permute - 원본 tensor와 메모리 공유 o

In [4]:
import torch 

x = torch.arange(1., 11.) 
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [5]:
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [8]:
x_stacked = torch.stack([x_reshaped, x_reshaped])
print(x_stacked.shape)
x_stacked

torch.Size([2, 2, 5])


tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]],

        [[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]])

In [9]:
x_hstacked = torch.hstack([x_reshaped, x_reshaped])
print(x_hstacked.shape)
x_hstacked

torch.Size([2, 10])


tensor([[ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.,  6.,  7.,  8.,  9., 10.]])

In [10]:
x_vstacked = torch.vstack([x_reshaped, x_reshaped])
print(x_vstacked.shape)
x_vstacked

torch.Size([4, 5])


tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [12]:
x_concatenated = torch.cat([x_reshaped, x_reshaped], dim=0)
print(x_concatenated.shape)
x_concatenated

torch.Size([4, 5])


tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [13]:
x_concatenated = torch.cat([x_reshaped, x_reshaped], dim=1)
print(x_concatenated.shape)
x_concatenated

torch.Size([2, 10])


tensor([[ 1.,  2.,  3.,  4.,  5.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.,  6.,  7.,  8.,  9., 10.]])

In [14]:
# indexing 
x = torch.arange(1, 10).reshape(1, 3, 3) 
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [15]:
x[0][1][1] 

tensor(5)

In [16]:
x[0, 1, 1]

tensor(5)

In [17]:
x[0, :, 1]

tensor([2, 5, 8])

In [18]:
x[:, :, 1]  # 인덱싱하면 차원이 줄어들고 슬라이싱하면 차원 유지 

tensor([[2, 5, 8]])

In [19]:
x[:, 0, :]

tensor([[1, 2, 3]])

In [20]:
x[..., 1]  #  x[:, :, 1]와 비슷. 하지만 x[..., 1]은 몇차원이든 사용 가능 

tensor([[2, 5, 8]])

* numpy는 기본 자료형이 float64, torch는 기본 자료형이 float32 
* numpy array -> torch tensor : `torch.from_numpy(ndarray).type(torch.float32)`
* torch tensor -> numpy array : `tensor.cpu().numpy()` 

In [23]:
import torch 
import numpy as np 

array = np.arange(1., 8.) 
print(array.dtype) 
array

float64


array([1., 2., 3., 4., 5., 6., 7.])

In [27]:
tensor = torch.from_numpy(array).type(torch.float32) 
print(tensor.dtype) 
tensor 

torch.float32


tensor([1., 2., 3., 4., 5., 6., 7.])

In [30]:
# randomness 

seed = 42 

torch.manual_seed(seed) 
a = torch.rand(2, 2) 

torch.manual_seed(seed)
b = torch.rand(2, 2)

a == b 

tensor([[True, True],
        [True, True]])

In [31]:
# check for GPU aceess with pytorch 

torch.cuda.is_available() 

False

In [32]:
# setup device agnostic code 

device = "cuda" if torch.cuda.is_available() else "cpu" 
device 

'cpu'

In [33]:
# count number of devices 
torch.cuda.device_count() 

0

In [35]:
# move tensor to GPU (if available) 
tensor_on_gpu = tensor.to(device) 
tensor_on_gpu.device

device(type='cpu')